# Generated by Django 4.2.4 on 2023-08-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('format', models.CharField(max_length=10)),
                ('document_file', models.FileField(upload_to='generated_documents/')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_generator.documenttemplate')),
            ],
        ),
    ]
