# Generated by Django 4.2.4 on 2023-08-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedDocument',
        ),
    ]
