# Generated by Django 4.2.4 on 2023-08-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0002_delete_generateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='template_document',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
