# Generated by Django 4.2.4 on 2023-08-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0005_alter_documenttemplate_data_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_document',
            field=models.FileField(blank=True, null=True, upload_to='todo/'),
        ),
    ]
